namespace QIndependentStudios.Obex
{
    public enum ObexResponseCode : byte
    {
        None = 0x00,
        NoneFinal = 0x0F,
        Continue = 0x90,
        Ok = 0xA0,
        Created = 0xA1,
        Accepted = 0xA2,
        NonAuthoritative = 0xA3,
        NoContent = 0xA4,
        ResetContent = 0xA5,
        PartialContent = 0xA6,
        MultipleChoices = 0xB0,
        MovedPermamently = 0xB1,
        MovedTemporarily = 0xB2,
        SeeOther = 0xB3,
        NotModified = 0xB4,
        UseProxy = 0xB5,
        BadRequest = 0xC0,
        Unauthorized = 0xC1,
        PaymentRequired = 0xC2,
        Forbidden = 0xC3,
        NotFound = 0xC4,
        MethodNotAllowed = 0xC5,
        NotAcceptable = 0xC6,
        ProxyAuthorizationRequired = 0xC7,
        RequestTimeout = 0xC8,
        Conflict = 0xC9,
        Gone = 0xCA,
        LengthRequired = 0xCB,
        PreconditionFailed = 0xCC,
        PayloadTooLarge = 0xCD,
        UriTooLarge = 0xCE,
        UnsupportedMediaType = 0xCF,
        InternalServerError = 0xD0,
        NotImplemented = 0xD1,
        BadGateway = 0xD2,
        ServiceUnavailable = 0xD3,
        GatewayTimeout = 0xD4,
        HttpVersionNotSupported = 0xD5,
        DatabaseFull = 0xE0,
        DatabaseLocked = 0xE1
    }
}
